### ISSUE TITLE
Vendor Admin Login Consultant Default Entries

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#42] opened 2016-11-03 10:35 UTC
![image](https://cloud.githubusercontent.com/assets/23167576/19962733/0b98a3f4-a1df-11e6-8d1a-4c31cf0db7ca.png)

I created new Vendor Just Now And Got 2 Consultants Defaultly without adding consultants .

**Comment by NaziniSK** [comment] 2016-11-03 12:38
same bug raising again and again?

**Comment by bhargavibindhu** [comment] 2016-11-04 07:40
Closing this bug as it is duplicate of #17

**Closed as completed by bhargavibindhu** 2016-11-04 07:40 UTC
Labels: duplicate
